# fly.toml app configuration file generated for ethg-brussels on 2024-07-13T16:27:06+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ethg-brussels'
primary_region = 'ams'

[build]

[env]
  PORT = "8000"

[[services]]
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
