export const enum Env {
  PORT = 'PORT',
  MODE = 'MODE',

  BASE_SEPOLIA_RPC_URL = 'BASE_SEPOLIA_RPC_URL',

  SALESFORCE_LOGIN_URL = 'SALESFORCE_LOGIN_URL',
  SALESFORCE_REDIRECT_URI = 'SALESFORCE_REDIRECT_URI',
  SALESFORCE_ORG_ID = 'SALESFORCE_ORG_ID',
  SALESFORCE_CLIENT_ID = 'SALESFORCE_CLIENT_ID',
  SALESFORCE_CLIENT_SECRET = 'SALESFORCE_CLIENT_SECRET',
}
